apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriapp01
spec:
  selector:
    matchLabels:
      app: sriapp01
  template:
    metadata:
      labels:
        app: sriapp01
    spec:
      containers:
      - name: sriapp01
        image: sbacr02.azurecr.io/sriapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
